--
-- Title: polaris_observation.psql
-- Description: polaris vessel observations
--
--
create table polaris_observation (
  id           bigserial   primary key,
 
  imo_code     varchar(24) unique not null,
  time_stamp   timestamp    not null,
);

grant select, insert, update, delete on polaris_observation to polaris_client;
grant usage, select on sequence polaris_observation_id_seq to polaris_client;

