--
-- Title: polaris_port.psql
-- Description: polaris port definitions
--
create table polaris_port (
  id           bigserial    primary key,
  locode       varchar(8)   unique not null,
  name         varchar(64)  unique not null,
  scrape_flag  boolean      not null default false,
  url          varchar(64)  unique not null
);

grant select, insert, update, delete on polaris_port to polaris_client;
grant usage, select on sequence polaris_port_id_seq to polaris_client;

insert into polaris_port(locode, name, scrape_flag, url) values('USBNC', 'Benicia',       true, 'https://www.vesselfinder.com/ports/USBNC001');
insert into polaris_port(locode, name, scrape_flag, url) values('USMRZ', 'Martinez',      true, 'https://www.vesselfinder.com/ports/USMRZ001');
insert into polaris_port(locode, name, scrape_flag, url) values('USRD4', 'Rodeo',         true, 'https://www.vesselfinder.com/ports/USRD4001');
insert into polaris_port(locode, name, scrape_flag, url) values('USSEL', 'Selby',         true, 'https://www.vesselfinder.com/ports/USSEL001');
insert into polaris_port(locode, name, scrape_flag, url) values('USCRM', 'Crockett',      true, 'https://www.vesselfinder.com/ports/USCRM001');
insert into polaris_port(locode, name, scrape_flag, url) values('USPZH', 'Port Chicago',  true, 'https://www.vesselfinder.com/ports/USPZH001');
insert into polaris_port(locode, name, scrape_flag, url) values('USPBG', 'Pittsburg',     true, 'https://www.vesselfinder.com/ports/USPBG001');
insert into polaris_port(locode, name, scrape_flag, url) values('USANZ', 'Antioch',       true, 'https://www.vesselfinder.com/ports/USANZ001');
insert into polaris_port(locode, name, scrape_flag, url) values('USOQY', 'Oakley',        true, 'https://www.vesselfinder.com/ports/USOQY001');
insert into polaris_port(locode, name, scrape_flag, url) values('USSAC', 'Sacramento',    true, 'https://www.vesselfinder.com/ports/USSAC001');
insert into polaris_port(locode, name, scrape_flag, url) values('USSCK', 'Stockton',      true, 'https://www.vesselfinder.com/ports/USSCK001');
insert into polaris_port(locode, name, scrape_flag, url) values('USRCH', 'Richmond',      true, 'https://www.vesselfinder.com/ports/USRCH001');
insert into polaris_port(locode, name, scrape_flag, url) values('USOAK', 'Oakland',       true, 'https://www.vesselfinder.com/ports/USOAK001');
insert into polaris_port(locode, name, scrape_flag, url) values('USSFO', 'San Francisco', true, 'https://www.vesselfinder.com/ports/USSFO001');
insert into polaris_port(locode, name, scrape_flag, url) values('USRWC', 'Redwood City',  true, 'https://www.vesselfinder.com/ports/USRWC002');
insert into polaris_port(locode, name, scrape_flag, url) values('USMY3', 'Monterey',      true, 'https://www.vesselfinder.com/ports/USMY3001');
insert into polaris_port(locode, name, scrape_flag, url) values('USFOB', 'Fort Bragg',    true, 'https://www.vesselfinder.com/ports/USFOB001');
insert into polaris_port(locode, name, scrape_flag, url) values('USEKA', 'Eureka',        true, 'https://www.vesselfinder.com/ports/USEKA001');
insert into polaris_port(locode, name, scrape_flag, url) values('USCEC', 'Crescent City', true, 'https://www.vesselfinder.com/ports/USCEC001');
insert into polaris_port(locode, name, scrape_flag, url) values('USVLO', 'Vallejo',       true, 'https://www.vesselfinder.com/ports/USVLO001');
insert into polaris_port(locode, name, scrape_flag, url) values('USPSL', 'Port San Luis', true, 'https://www.vesselfinder.com/ports/USPSL001');
insert into polaris_port(locode, name, scrape_flag, url) values('USNTD', 'Port Hueneme',  true, 'https://www.vesselfinder.com/ports/USNTD001');

insert into polaris_port(locode, name, scrape_flag, url) values('USPDX', 'Portland',         false, 'https://www.vesselfinder.com/ports/USPDX002');
insert into polaris_port(locode, name, scrape_flag, url) values('USVAN', 'Vancouver',        false, 'https://www.vesselfinder.com/ports/USVAN001');
insert into polaris_port(locode, name, scrape_flag, url) values('USSEA', 'Seattle',          false, 'https://www.vesselfinder.com/ports/USSEA001');
insert into polaris_port(locode, name, scrape_flag, url) values('USTIW', 'Tacoma',           false, 'https://www.vesselfinder.com/ports/USTIW001');
insert into polaris_port(locode, name, scrape_flag, url) values('USLAX', 'Los Angeles',      false, 'https://www.vesselfinder.com/ports/USLAX001');
insert into polaris_port(locode, name, scrape_flag, url) values('USHNL', 'Honolulu',         false, 'https://www.vesselfinder.com/ports/USHNL001');
insert into polaris_port(locode, name, scrape_flag, url) values('KRBNP', 'Busan New Port',   false, 'https://www.vesselfinder.com/ports/KRBNP001');
insert into polaris_port(locode, name, scrape_flag, url) values('PAPCN', 'Panama Canal',     false, 'https://www.vesselfinder.com/ports/PAPCN006');
insert into polaris_port(locode, name, scrape_flag, url) values('NLRTM', 'Rotterdam',        false, 'https://www.vesselfinder.com/ports/NLRTM001');
insert into polaris_port(locode, name, scrape_flag, url) values('HKHKG', 'Hong Kong',        false, 'https://www.vesselfinder.com/ports/HKHKG001');
insert into polaris_port(locode, name, scrape_flag, url) values('JPYAT', 'Yatsushiro',       false, 'https://www.vesselfinder.com/ports/JPYAT001');
insert into polaris_port(locode, name, scrape_flag, url) values('MXTPB', 'Topolobampo',      false, 'https://www.vesselfinder.com/ports/MXTPB001');
insert into polaris_port(locode, name, scrape_flag, url) values('TWKHH', 'Kaohsiung',        false, 'https://www.vesselfinder.com/ports/TWKHH001');
insert into polaris_port(locode, name, scrape_flag, url) values('JPTMK', 'Tomakomai',        false, 'https://www.vesselfinder.com/ports/JPTMK001');
insert into polaris_port(locode, name, scrape_flag, url) values('MYBTU', 'Bintulu',          false, 'https://www.vesselfinder.com/ports/MYBTU001');
insert into polaris_port(locode, name, scrape_flag, url) values('JPSKD', 'Sakaide',          false, 'https://www.vesselfinder.com/ports/JPSKD001');
insert into polaris_port(locode, name, scrape_flag, url) values('JPSAK', 'Sakai',            false, 'https://www.vesselfinder.com/ports/JPSAK001');
insert into polaris_port(locode, name, scrape_flag, url) values('KRMAS', 'Masan',            false, 'https://www.vesselfinder.com/ports/KRMAS001');
insert into polaris_port(locode, name, scrape_flag, url) values('KRUSN', 'Ulsan',            false, 'https://www.vesselfinder.com/ports/KRUSN001');
insert into polaris_port(locode, name, scrape_flag, url) values('USFDT', 'Ferndale',         false, 'https://www.vesselfinder.com/ports/USFDT001');
insert into polaris_port(locode, name, scrape_flag, url) values('CAPMA', 'Port McNeill',     false, 'https://www.vesselfinder.com/ports/CAPMA001');
insert into polaris_port(locode, name, scrape_flag, url) values('CAVAN', 'Vancouver',        false, 'https://www.vesselfinder.com/ports/CAVAN001');
insert into polaris_port(locode, name, scrape_flag, url) values('CAVAC', 'North Vancouver',  false, 'https://www.vesselfinder.com/ports/CAVAC001');
insert into polaris_port(locode, name, scrape_flag, url) values('JPSGM', 'Sendai',           false, 'https://www.vesselfinder.com/ports/JPSGM001');
insert into polaris_port(locode, name, scrape_flag, url) values('PABLB', 'Balboa',           false, 'https://www.vesselfinder.com/ports/PABLB001');
insert into polaris_port(locode, name, scrape_flag, url) values('USKAM', 'Kalama',           false, 'https://www.vesselfinder.com/ports/USKAM001');
insert into polaris_port(locode, name, scrape_flag, url) values('KRMAS', 'Masan',            false, 'https://www.vesselfinder.com/ports/KRMAS001');
insert into polaris_port(locode, name, scrape_flag, url) values('KRPUS', 'Busan',            false, 'https://www.vesselfinder.com/ports/KRBNP001');
insert into polaris_port(locode, name, scrape_flag, url) values('JPYOK', 'Yokohama',         false, 'https://www.vesselfinder.com/ports/JPYOK001');
insert into polaris_port(locode, name, scrape_flag, url) values('GTPRQ', 'Puerto Quetzal',   false, 'https://www.vesselfinder.com/ports/GTPRQ001');
insert into polaris_port(locode, name, scrape_flag, url) values('MXLZC', 'Lazaro Cardenas',  false, 'https://www.vesselfinder.com/ports/MXLZC001');
insert into polaris_port(locode, name, scrape_flag, url) values('ECGYE', 'Guayaquil',        false, 'https://www.vesselfinder.com/ports/ECGYE001');
insert into polaris_port(locode, name, scrape_flag, url) values('USLGB', 'Long Beach',       false, 'https://www.vesselfinder.com/ports/USLGB001');
insert into polaris_port(locode, name, scrape_flag, url) values('USELS', 'El Segundo',       false, 'https://www.vesselfinder.com/ports/USELS002');
insert into polaris_port(locode, name, scrape_flag, url) values('PAAML', 'Puerto Armuelles', false, 'https://www.vesselfinder.com/ports/PAAML001');
insert into polaris_port(locode, name, scrape_flag, url) values('JPTHS', 'Toyohashi',        false, 'https://www.vesselfinder.com/ports/JPTHS001');
